services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    restart: "no"
    command: >
      cargo watch
      -x 'run --bin rust-api-starter'
    environment:
      LOG_DIR: /app/logs
      UPLOAD_DIR: /app/uploads
      RUST_LOG: debug,actix_web=info
    volumes:
      - .:/app
      - cargo-registry:/usr/local/cargo/registry
      - cargo-git:/usr/local/cargo/git
      - cargo-target:/app/target
      - ./logs:/app/logs
      - ./uploads:/app/uploads

volumes:
  cargo-registry:
  cargo-git:
  cargo-target:
